### ISSUE TITLE
unable to view or download the Overview_LSMA_in_Python.ipynb

### ISSUE THREAD

**Issue by astroindhu** [arthur-e/unmixing#6]
I am unable to view Overview_LSMA_in_Python.ipynb in github or even open the downloaded file in jupyter. I want to try this out

**Comment by arthur-e** [comment]
Hi @astroindhu, there is nothing wrong with [the iPython Notebook on Github](https://github.com/arthur-e/unmixing/blob/master/docs/Overview_LSMA_in_Python.ipynb). I just tried it again on a moderately slow public wi-fi network. Are you seeing a loading indicator? That is normal for a file like this; the full notebook loaded in less than 10 seconds for me.

Perhaps try a different web browser? Or try upgrading your web browser. I have tried this on Google Chrome on Mac OSX and Ubuntu GNU/ Linux.

As for getting it to run on your local machine, that is more challenging as you'll have to set up your Python environment and install the dependencies. Please post any errors you are getting in that process in detail.

**Comment by astroindhu** [comment]
when i install requirements, i get this error 
 Could not find a version that satisfies the requirement python-dateutil==2.0 (from -r REQUIREMENTS (line 9)) (from versions: 1.4, 1.4.1, 1.5, 2.1, 2.2, 2.3, 2.4.0, 2.4.1, 2.4.1.post1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1)
No matching distribution found for python-dateutil==2.0 (from -r REQUIREMENTS (line 9))

however, I changed the REQUIREMENTS file from python-dateutil==2.0 to python-dateutil and now it works. Thought you should update this !

**Comment by arthur-e** [comment]
Great, thanks, this sometimes happens with the `REQUIREMENTS` file when it is dumped from `pip freeze`. Removing the version numbers or running `pip install <packagename>` is the correct solution.
